### ISSUE TITLE
Teacher Review Week 4

### ISSUE THREAD

**Issue by rpeddakama** [raad1masum/AP-CSA-Tri-1-Project#15]

**Comment by jm1021** [comment]
Good overview of issues.   Assignment to individuals are clear.  Big ideas in future.  1.0

**Comment by jm1021** [comment]
Rishi, 
1. looks like credit for work on Binary integration, though issue is not defined
2. video was only by Rishi, no other participants clarifying contributions
3. journal is outstanding, test scores verified
4. team work is show no progression over last week, still just a home screen

3/5 on individual and team, 5/5 on journal and test prep

**Comment by jm1021** [comment]
Raadwan, 
1. I spent a lot of time trying to figure out what you did in PBL, README seems to indicate you did something with home page, but that is same thing I did last week.
2.  no journal, but test scores on AP

2/5 on individual and team, 2.5/5 on journal test prep

**Comment by jm1021** [comment]
Anrav, 
1. no tickets in review, link on issue on readme is blank
2. good notes in journal and on Tech Talk

2/5 on individual and team, 5/5 on journal

**Comment by jm1021** [comment]
Aman,
1. no tickets in review, issue is blank, noting in review
2. journal has restricted access, verified doing work on CB

2/5 on individual, 2.5 on journal

**Comment by jm1021** [comment]
All in all, I spent way to much time looking for your materials.  Over 30 minutes.  You need a lot of improvment.

**Comment by jm1021** [comment]
Please link this review into your Week 4 Time box.
