### ISSUE TITLE
Style curvy layout

### ISSUE THREAD

**Issue by rpeddakama** [raad1masum/AP-CSA-Tri-1-Project#2]

**Comment by raad1masum** [comment]
Homepage layout is complete, located [here](https://www.figma.com/file/Gwml5xTAfzebPmFUXSoqm4/AP-CSA-Project?node-id=0%3A1).

**Comment by rpeddakama** [comment]
![Screenshot 2021-09-12 231201](https://user-images.githubusercontent.com/55494721/133032531-2c58eada-8902-4617-8f19-3a4ca44cb0bb.png)
The picture above shows the curvy layout implemented in html
