### ISSUE TITLE
Loops Minilab (extra credit)

### ISSUE THREAD

**Issue by rpeddakama** [raad1masum/AP-CSA-Tri-1-Project#25]

**Comment by raad1masum** [comment]
![image](https://user-images.githubusercontent.com/39575185/134391280-82999288-8bf3-4353-ae8d-030c16e58fcd.png)

**Comment by raad1masum** [comment]
![image](https://user-images.githubusercontent.com/39575185/134391350-c0f6b244-0b3b-41a1-af46-e069854fb7ef.png)

**Comment by raad1masum** [comment]
![image](https://user-images.githubusercontent.com/39575185/134391429-32575880-b090-4cf6-849f-e7c4a18f77b8.png)

**Comment by raad1masum** [comment]
![image](https://user-images.githubusercontent.com/39575185/134391475-a55eeaf2-81eb-42b0-bb04-a9b23fca4c70.png)

**Comment by avabrooks** [comment]
+0.5 extra credit for completed TPT Mini Lab.
