### ISSUE TITLE
Planning Ticket for Wednesday

### ISSUE THREAD

**Issue by rpeddakama** [raad1masum/AP-CSA-Tri-1-Project#36]

**Comment by rpeddakama** [comment]
[View Frontend](https://github.com/raad1masum/AP-CSA-Tri-1-Project/issues/31)
[Control Improvements](https://github.com/raad1masum/AP-CSA-Tri-1-Project/issues/32)
[Model Improvements](https://github.com/raad1masum/AP-CSA-Tri-1-Project/issues/33)

**Comment by jm1021** [comment]
Nice capture above showing key areas.  Nice checckbox and individuals assignments.  Talk about different algos.  Talked about frontend usability.  Discussed and showed great secondary thinking in Control.   1/1
