### ISSUE TITLE
Greet

### ISSUE THREAD

**Issue by rpeddakama** [raad1masum/AP-CSA-Tri-1-Project#4]

**Comment by ArnavPalkhiwala** [comment]
![Screen Shot 2021-09-12 at 10 58 40 PM](https://user-images.githubusercontent.com/25650329/133031224-87b0faa0-086c-417b-b2fb-16a4e29aca17.png)

**Comment by rpeddakama** [comment]
The picture above contains 2 forms. One for a simple greet (it takes in a name and prints it below with a static message prepended to it). The other takes in a number and returns the value squared.
