### ISSUE TITLE
Week 8 Review Ticket

### ISSUE THREAD

**Issue by ArnavPalkhiwala** [raad1masum/AP-CSA-Tri-1-Project#40]
Presentation Feedback from Mr. M and fellow students:

Please comment on any feedback from or presentation that we can use to improve our project and presentation skills for the future. Thank you!

[Link to Deployed Project](http://54.219.237.101/)

[Presentation Link](https://docs.google.com/presentation/d/1xEOpT77B031Rhh03qBxSFHKKm6nO-wvmFmwF4_lTP1Q/edit?usp=sharing)

**Comment by avabrooks** [comment]
I really like the website conflict and great job on deployment

**Comment by elw55555** [comment]
I like the purpose of your website, I find myself using it in the future.

**Comment by TMarwah** [comment]
I love the purpose of your website! It reminds me of obscurify, which has a similar function

**Comment by Navodit1603** [comment]
I really liked the idea and your plan to use spotify api. I also like the css on the pages, theme seems very relaxing. It is interesting that you guys used AWS.

**Comment by algolg** [comment]
Frontend looks great and matches with your Spotify theme

**Comment by adritac-tech** [comment]
It was really cool how you explained deployment and I liked the concept of finding statistics about certain playlists.
