### ISSUE TITLE
Formulate ideation (feedback system)

### ISSUE THREAD

**Issue by rpeddakama** [raad1masum/AP-CSA-Tri-1-Project#5]

**Comment by ArnavPalkhiwala** [comment]
The overall idea of our project is an anonymous feedback system for Del Norte High School. People will be able to post ideas and have students anonymously give their opinions on it. We hope that it becomes useful for teachers (for evaluating their lesson plans) and for ASB (when planning future events).

**Comment by rpeddakama** [comment]
The location of this ideation can be found in a past readme [here](https://github.com/raad1masum/AP-CSA-Tri-1-Project/blob/main/PastREADMES/Week1-2_README.md)
